# Generated by Django 5.0.7 on 2025-12-29 08:52

from django.db import migrations
from django.utils.text import slugify


def create_initial_services(apps, schema_editor):
    ServiceCategory = apps.get_model('services', 'ServiceCategory')
    Service = apps.get_model('services', 'Service')
    
    # Создаем категории если их нет
    cat1, _ = ServiceCategory.objects.get_or_create(
        slug='proektirovanie',
        defaults={
            'name': 'Проектирование',
            'order': 1,
            'is_active': True
        }
    )
    
    cat2, _ = ServiceCategory.objects.get_or_create(
        slug='stroitelstvo',
        defaults={
            'name': 'Строительство',
            'order': 2,
            'is_active': True
        }
    )
    
    cat3, _ = ServiceCategory.objects.get_or_create(
        slug='izyiskaniya',
        defaults={
            'name': 'Изыскания',
            'order': 3,
            'is_active': True
        }
    )
    
    cat4, _ = ServiceCategory.objects.get_or_create(
        slug='dorogi',
        defaults={
            'name': 'Дороги',
            'order': 4,
            'is_active': True
        }
    )
    
    # Услуги для категории "Проектирование"
    services_data = [
        (cat1, 'Генеральный план и градостроительство', 'Разработка генеральных планов и градостроительных решений'),
        (cat1, 'Архитектурно-строительное проектирование', 'Полный комплекс архитектурно-строительного проектирования'),
        (cat1, 'Технологическое проектирование (ТХ)', 'Технологическое проектирование промышленных объектов'),
        (cat1, 'Проектирование трубопроводов', 'Проектирование трубопроводных систем различного назначения'),
        (cat1, 'Электроснабжение и электроосвещение', 'Проектирование систем электроснабжения и освещения'),
        (cat1, 'Отопление, вентиляция и кондиционирование (ОВиК)', 'Проектирование систем отопления, вентиляции и кондиционирования'),
        (cat1, 'КИПиА и автоматизация', 'Проектирование систем контроля, измерения и автоматизации'),
        (cat4, 'Автомобильные и железные дороги', 'Проектирование и строительство автомобильных и железных дорог'),
        (cat3, 'Инженерно-геодезические работы', 'Комплекс инженерно-геодезических изысканий'),
        (cat3, 'Инженерно-геологические изыскания', 'Инженерно-геологические исследования и изыскания'),
    ]
    
    for category, name, description in services_data:
        slug = slugify(name)
        Service.objects.get_or_create(
            slug=slug,
            defaults={
                'name': name,
                'category': category,
                'short_description': description,
                'full_description': description,
                'order': 0,
                'is_active': True
            }
        )


def reverse_migration(apps, schema_editor):
    ServiceCategory = apps.get_model('services', 'ServiceCategory')
    Service = apps.get_model('services', 'Service')
    
    # Удаляем созданные услуги
    Service.objects.filter(slug__in=[
        'generalnyy-plan-i-gradostroitelstvo',
        'arhitekturno-stroitelnoe-proektirovanie',
        'tehnologicheskoe-proektirovanie-th',
        'proektirovanie-truboprovodov',
        'elektrosnabzhenie-i-elektroosveschenie',
        'otoplenie-ventilyaciya-i-kondicionirovanie-ovik',
        'kipia-i-avtomatizaciya',
        'avtomobilnye-i-zheleznye-dorogi',
        'inzhenerno-geodezicheskie-raboty',
        'inzhenerno-geologicheskie-izyiskaniya',
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_services, reverse_migration),
    ]
