# Generated by Django 5.0.7 on 2025-12-29 08:56

from django.db import migrations
from django.utils.text import slugify


def fix_empty_slugs(apps, schema_editor):
    Service = apps.get_model('services', 'Service')
    ServiceCategory = apps.get_model('services', 'ServiceCategory')
    
    # Исправляем услуги с пустым slug
    services = Service.objects.filter(slug='')
    for service in services:
        if service.name:
            base_slug = slugify(service.name)
            if not base_slug:
                base_slug = f'service-{service.id}'
            
            # Проверяем уникальность
            slug = base_slug
            counter = 1
            while Service.objects.filter(slug=slug).exclude(id=service.id).exists():
                slug = f'{base_slug}-{counter}'
                counter += 1
            
            service.slug = slug
            service.save()
    
    # Исправляем категории с пустым slug
    categories = ServiceCategory.objects.filter(slug='')
    for category in categories:
        if category.name:
            base_slug = slugify(category.name)
            if not base_slug:
                base_slug = f'category-{category.id}'
            
            # Проверяем уникальность
            slug = base_slug
            counter = 1
            while ServiceCategory.objects.filter(slug=slug).exclude(id=category.id).exists():
                slug = f'{base_slug}-{counter}'
                counter += 1
            
            category.slug = slug
            category.save()


def reverse_migration(apps, schema_editor):
    # Нечего откатывать
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_add_initial_services'),
    ]

    operations = [
        migrations.RunPython(fix_empty_slugs, reverse_migration),
    ]
