# Generated by Django 5.0.7 on 2025-12-27 12:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('title', models.CharField(max_length=200, verbose_name='Название сертификата')),
                ('number', models.CharField(max_length=100, verbose_name='Номер сертификата')),
                ('issue_date', models.DateField(verbose_name='Дата выдачи')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('issuer', models.CharField(max_length=200, verbose_name='Выдавший орган')),
                ('image', models.ImageField(upload_to='certificates/', verbose_name='Изображение сертификата')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('name', models.CharField(max_length=200, verbose_name='Название клиента')),
                ('logo', models.ImageField(upload_to='clients/', verbose_name='Логотип')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('name', models.CharField(max_length=200, verbose_name='Название компании')),
                ('short_description', ckeditor.fields.RichTextField(verbose_name='Краткое описание')),
                ('full_description', ckeditor.fields.RichTextField(verbose_name='Полное описание')),
                ('founded_year', models.PositiveIntegerField(verbose_name='Год основания')),
                ('mission', ckeditor.fields.RichTextField(blank=True, verbose_name='Миссия')),
                ('vision', ckeditor.fields.RichTextField(blank=True, verbose_name='Видение')),
                ('values', ckeditor.fields.RichTextField(blank=True, verbose_name='Ценности')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address_almaty', models.TextField(verbose_name='Адрес в Алматы')),
                ('address_atyrau', models.TextField(blank=True, verbose_name='Адрес в Атырау')),
                ('working_hours', models.CharField(max_length=100, verbose_name='Режим работы')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta Description')),
            ],
            options={
                'verbose_name': 'Информация о компании',
                'verbose_name_plural': 'Информация о компании',
            },
        ),
        migrations.CreateModel(
            name='KeyFigure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('value', models.CharField(max_length=50, verbose_name='Значение')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Иконка (emoji)')),
            ],
            options={
                'verbose_name': 'Ключевая цифра',
                'verbose_name_plural': 'Ключевые цифры',
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('title', models.CharField(max_length=200, verbose_name='Название лицензии')),
                ('number', models.CharField(max_length=100, verbose_name='Номер лицензии')),
                ('issue_date', models.DateField(verbose_name='Дата выдачи')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('issuer', models.CharField(max_length=200, verbose_name='Выдавший орган')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
                ('image', models.ImageField(upload_to='licenses/', verbose_name='Изображение лицензии')),
            ],
            options={
                'verbose_name': 'Лицензия',
                'verbose_name_plural': 'Лицензии',
            },
        ),
    ]
