# Generated by Django 5.0.7 on 2025-12-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Партнер', 'verbose_name_plural': 'Наши партнеры'},
        ),
        migrations.RemoveField(
            model_name='client',
            name='description',
        ),
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
        migrations.AlterField(
            model_name='client',
            name='logo',
            field=models.ImageField(upload_to='clients/', verbose_name='Логотип партнера'),
        ),
        migrations.AlterField(
            model_name='client',
            name='website',
            field=models.URLField(blank=True, verbose_name='Ссылка на сайт'),
        ),
    ]
