# Generated by Django 5.0.7 on 2025-12-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_client_options_remove_client_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='category',
        ),
        migrations.RemoveField(
            model_name='license',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='license',
            name='issue_date',
        ),
        migrations.RemoveField(
            model_name='license',
            name='issuer',
        ),
        migrations.RemoveField(
            model_name='license',
            name='number',
        ),
        migrations.AlterField(
            model_name='license',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название лицензии'),
        ),
    ]
