# Generated by Django 5.0.7 on 2025-12-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_license_category_remove_license_expiry_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='image',
        ),
        migrations.AddField(
            model_name='license',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='licenses/', verbose_name='Файл лицензии (изображение или PDF)'),
        ),
    ]
