# Generated by Django 5.0.7 on 2025-12-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_license_image_license_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('name', models.CharField(max_length=200, verbose_name='Название услуги')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL (для якорной ссылки)')),
                ('description', models.TextField(verbose_name='Описание услуги')),
                ('icon_svg', models.TextField(blank=True, help_text='Вставьте SVG код иконки. Если не указано, будет использована стандартная иконка.', verbose_name='SVG код иконки')),
            ],
            options={
                'verbose_name': 'Услуга на главной',
                'verbose_name_plural': 'Услуги на главной',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
