# Generated by Django 5.0.7 on 2025-12-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_homeservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Название проекта')),
                ('image', models.ImageField(upload_to='home_projects/', verbose_name='Изображение проекта')),
            ],
            options={
                'verbose_name': 'Изображение проекта на главной',
                'verbose_name_plural': 'Изображения проектов на главной',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
