# Generated by Django 5.0.7 on 2025-12-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_homeprojectimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhoWeAreImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Название изображения')),
                ('image', models.ImageField(upload_to='who_we_are/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': "Изображение для секции 'КТО МЫ'",
                'verbose_name_plural': "Изображения для секции 'КТО МЫ'",
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
