# Generated by Django 5.0.7 on 2025-12-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_whoweareimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Оставьте пустым, если сертификат бессрочный', null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='image',
            field=models.ImageField(help_text='Загрузите изображение сертификата (JPG, PNG). Рекомендуемый размер: не менее 800x1000 пикселей', upload_to='certificates/', verbose_name='Изображение сертификата'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='issue_date',
            field=models.DateField(help_text='Дата, когда был выдан сертификат (формат: ДД.ММ.ГГГГ)', verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='issuer',
            field=models.CharField(help_text='Например: Министерство индустрии и инфраструктурного развития РК', max_length=200, verbose_name='Выдавший орган'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='number',
            field=models.CharField(help_text='Например: KZ.16.01.01.001.Е.000001.01.06', max_length=100, verbose_name='Номер сертификата'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='title',
            field=models.CharField(help_text='Например: Лицензия на строительно-монтажные работы 1 категории', max_length=200, verbose_name='Название сертификата'),
        ),
    ]
